name: cloudwatch-exporter CICD
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  buildDockerImage:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build docker image for arm64
      run: docker build -t yace-arm64 --build-arg GOARCH=arm64  --build-arg VERSION=${{github.event.release.tag_name}} .
    - name: "Login to Docker Hub"
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Tag docker image arm
      run: docker tag yace-arm64 kubestar/cloudwatch-exporter:support-docker-arm-2024-05-10-arm64
    - name: Publish docker image arm64
      run: docker push kubestar/cloudwatch-exporter:support-docker-arm-2024-05-10-arm64
